#!/usr/bin/env tsx
/**
 * Projects Data Generator
 * 
 * Generates src/data/projects-data.ts from github-repos.json
 * This replaces the manual merge-metadata.js script
 */

import { readFileSync, writeFileSync, existsSync } from 'fs'
import { join, dirname } from 'path'
import { fileURLToPath } from 'url'

const __dirname = dirname(fileURLToPath(import.meta.url))

interface RepoMetadata {
  repo: string
  url: string
  description: string
  last_updated: string
  latest_commit: string
  commit_sha: string | null
  commit_date: string
  commit_message: string
  author: string
  issues: number
  stars: number
  forks: number
  watchers: number
  ci_cd_status: 'pass' | 'fail' | 'running' | 'none'
  languages: string[]
  license: string
  topics: string[]
  raw_updated_at: string
}

interface Project {
  title: string
  techStack: string[]
  description: string
  link: {
    label: string
    href: string
  }
  stars: number
  forks: number
  issues: number
  lastUpdated: string
  lastCommit: string
}

function formatTitle(repoName: string): string {
  // Convert repo name to readable title
  return repoName
    .replace(/-/g, ' ')
    .replace(/_/g, ' ')
    .replace(/([A-Z])/g, ' $1')
    .replace(/^\w/, c => c.toUpperCase())
    .trim()
}

function generateTechStack(repo: RepoMetadata): string[] {
  // Combine topics and languages, prioritize topics
  const tags = [...new Set([...repo.topics, ...repo.languages])]
  return tags.slice(0, 6)
}

function generateDescription(repo: RepoMetadata): string {
  const desc = repo.description || 'No description provided.'
  // Truncate if too long
  if (desc.length > 200) {
    return desc.slice(0, 197).trimEnd() + '...'
  }
  return desc
}

async function main(): Promise<void> {
  const dataPath = join(__dirname, '..', 'data', 'github-repos.json')
  const projectsPath = join(__dirname, '..', 'src', 'data', 'projects-data.ts')

  if (!existsSync(dataPath)) {
    console.error('❌ github-repos.json not found. Run fetch-github-data.ts first.')
    process.exit(1)
  }

  const repos: RepoMetadata[] = JSON.parse(readFileSync(dataPath, 'utf8'))
  console.log(`📖 Loaded ${repos.length} repositories from data`)

  const projects: Project[] = repos.map(repo => ({
    title: formatTitle(repo.repo),
    techStack: generateTechStack(repo),
    description: generateDescription(repo),
    link: {
      label: `github.com/${repo.repo}`,
      href: repo.url,
    },
    stars: repo.stars,
    forks: repo.forks,
    issues: repo.issues,
    lastUpdated: repo.raw_updated_at,
    lastCommit: repo.commit_sha || 'unknown',
  }))

  // Generate the TypeScript file
  const header = `// src/data/projects-data.ts
// AUTO-GENERATED by scripts/generate-projects-data.ts
// DO NOT EDIT MANUALLY - changes will be overwritten

interface Project {
  title: string;
  techStack: string[];
  description: string;
  link: {
    label: string;
    href: string;
  };
  stars: number;
  forks: number;
  issues: number;
  lastUpdated: string;
  lastCommit: string;
}

export const PROJECTS: Project[] = `

  const content = `${header}${JSON.stringify(projects, null, 2)};\n`

  writeFileSync(projectsPath, content)
  console.log(`✅ Generated ${projectsPath} with ${projects.length} projects`)
}

main().catch((err: Error) => {
  console.error('❌ Fatal error:', err)
  process.exit(1)
})