// src/data/projects-data.ts
// AUTO-GENERATED by scripts/generate-projects-data.ts
// DO NOT EDIT MANUALLY - changes will be overwritten

interface Project {
  title: string;
  techStack: string[];
  description: string;
  link: {
    label: string;
    href: string;
  };
  stars: number;
  forks: number;
  issues: number;
  lastUpdated: string;
  lastCommit: string;
}

export const PROJECTS: Project[] = [
  {
    "title": "Dev Ops  Projects",
    "techStack": [
      "aws",
      "beginner-friendly",
      "devops",
      "devops-learning",
      "devops-poc",
      "devops-project"
    ],
    "description": "🚀 Real-world DevOps projects for aspiring engineers — Beginner to Advanced. Covers AWS, Kubernetes, Docker, CI/CD, Terraform, Jenkins, and more. Hands-on learning with step-by-step guides.",
    "link": {
      "label": "github.com/DevOps-Projects",
      "href": "https://github.com/NotHarshhaa/DevOps-Projects"
    },
    "stars": 5347,
    "forks": 4845,
    "issues": 30,
    "lastUpdated": "2026-10-09T18:48:12Z",
    "lastCommit": "7482982bb88f59e1a1bd1d5e57600d69a1c48d2d"
  },
  {
    "title": "Dev Ops  Interview  Questions",
    "techStack": [
      "aws-interview-questions",
      "azure-interview-questions",
      "cicd",
      "cloud-computing",
      "devops",
      "devops-interview-questions"
    ],
    "description": "Collection of 2,200+ DevOps, SRE & Platform Engineering interview questions with in-depth answers covering CI/CD, GitOps, Cloud (AWS, Azure, GCP), Kubernetes, Terraform, OpenTofu, Linux, Observabil...",
    "link": {
      "label": "github.com/DevOps-Interview-Questions",
      "href": "https://github.com/NotHarshhaa/DevOps-Interview-Questions"
    },
    "stars": 1246,
    "forks": 917,
    "issues": 4,
    "lastUpdated": "2026-10-09T14:08:56Z",
    "lastCommit": "5081cf61629271e8e723d655db2f58a41ba1f993"
  },
  {
    "title": "Into the devops",
    "techStack": [
      "ansible",
      "aws",
      "azure",
      "coding",
      "containers",
      "devops"
    ],
    "description": "𝖫𝗂𝗇𝗎𝗑, 𝖩𝖾𝗇𝗄𝗂𝗇𝗌, 𝖠𝖶𝖲, 𝖲𝖱𝖤, 𝖯𝗋𝗈𝗆𝖾𝗍𝗁𝖾𝗎𝗌, 𝖣𝗈𝖼𝗄𝖾𝗋, 𝖯𝗒𝗍𝗁𝗈𝗇, 𝖠𝗇𝗌𝗂𝖻𝗅𝖾, 𝖦𝗂𝗍, 𝖪𝗎𝖻𝖾𝗋𝗇𝖾𝗍𝖾𝗌, 𝖳𝖾𝗋𝗋𝖺𝖿𝗈𝗋𝗆, 𝖮𝗉𝖾𝗇𝖲𝗍𝖺𝖼𝗄, 𝖲𝖰𝖫, 𝖭𝗈𝖲𝖰\ud835...",
    "link": {
      "label": "github.com/into-the-devops",
      "href": "https://github.com/NotHarshhaa/into-the-devops"
    },
    "stars": 916,
    "forks": 544,
    "issues": 0,
    "lastUpdated": "2026-10-09T17:19:52Z",
    "lastCommit": "1fef40a47764021ca15eb1e227502a6e64787176"
  },
  {
    "title": "Kubernetes learning path",
    "techStack": [
      "beginner",
      "kubernetes",
      "kubernetes-best-practices",
      "kubernetes-deployment",
      "kubernetes-roadmap",
      "kubernetes-setup"
    ],
    "description": "𝘼 𝙧𝙤𝙖𝙙𝙢𝙖𝙥 𝙩𝙤 𝙡𝙚𝙖𝙧𝙣 𝙆𝙪𝙗𝙚𝙧𝙣𝙚𝙩𝙚𝙨 𝙛𝙧𝙤𝙢 𝙨𝙘𝙧𝙖𝙩𝙘𝙝 (𝘽𝙚𝙜𝙞𝙣𝙣𝙚𝙧 𝙩𝙤 𝘼𝙙𝙫𝙖𝙣𝙘𝙚𝙙 𝙡𝙚𝙫𝙚𝙡)",
    "link": {
      "label": "github.com/kubernetes-learning-path",
      "href": "https://github.com/NotHarshhaa/kubernetes-learning-path"
    },
    "stars": 630,
    "forks": 233,
    "issues": 4,
    "lastUpdated": "2026-10-09T12:16:03Z",
    "lastCommit": "734c2cf7233dcca42bbb66203b764f4a462e00dd"
  },
  {
    "title": "Kubernetes projects learning",
    "techStack": [
      "devops",
      "devopsproject",
      "kubernetes",
      "kubernetes-cluster",
      "kubernetes-deployment",
      "kubernetes-learning"
    ],
    "description": "𝘼 𝙧𝙚𝙥𝙤 𝙩𝙤 𝙝𝙚𝙡𝙥 𝙮𝙤𝙪 𝙋𝙧𝙖𝙘𝙩𝙞𝙨𝙚 𝙆𝙪𝙗𝙚𝙧𝙣𝙚𝙩𝙚𝙨 𝙛𝙧𝙤𝙢 𝙩𝙝𝙚 𝙜𝙧𝙤𝙪𝙣𝙙 𝙪𝙥 𝙗𝙮 𝙙𝙤𝙞𝙣𝙜 𝙥𝙧𝙖𝙘𝙩𝙞𝙘𝙖𝙡 𝙍𝙚𝙖𝙡𝙩𝙞𝙢𝙚 𝙥𝙧𝙤𝙟𝙚𝙘𝙩𝙨 𝙖𝙣𝙙 𝙩𝙚𝙖𝙘𝙝 𝙮𝙤\ud835...",
    "link": {
      "label": "github.com/kubernetes-projects-learning",
      "href": "https://github.com/NotHarshhaa/kubernetes-projects-learning"
    },
    "stars": 524,
    "forks": 394,
    "issues": 1,
    "lastUpdated": "2026-10-07T09:10:10Z",
    "lastCommit": "dee8ff4607954972994dedc5689390ffd8ad01b7"
  },
  {
    "title": "Devops cheatsheet",
    "techStack": [
      "automation",
      "aws",
      "azure",
      "cheatsheet",
      "cicd",
      "cloud"
    ],
    "description": "A comprehensive collection of quick-reference cheatsheets for DevOps tools, covering CI/CD, containerization, monitoring, security, cloud infrastructure, and networking. Perfect for DevOps engineer...",
    "link": {
      "label": "github.com/devops-cheatsheet",
      "href": "https://github.com/NotHarshhaa/devops-cheatsheet"
    },
    "stars": 367,
    "forks": 272,
    "issues": 3,
    "lastUpdated": "2026-10-08T00:29:37Z",
    "lastCommit": "7b41362c58712bb1b094d8175444b39bf84ade66"
  },
  {
    "title": "Devops tools",
    "techStack": [
      "devops",
      "devops-tools",
      "devops-tools-support",
      "devopstool",
      "devopstoolkit",
      "devopstools"
    ],
    "description": "A comprehensive collection of essential DevOps tools for development, deployment, monitoring, automation, security, and more. Whether you're a beginner exploring DevOps or a seasoned engineer looki...",
    "link": {
      "label": "github.com/devops-tools",
      "href": "https://github.com/NotHarshhaa/devops-tools"
    },
    "stars": 241,
    "forks": 162,
    "issues": 4,
    "lastUpdated": "2026-10-01T11:53:15Z",
    "lastCommit": "cd2efbc8b4fb93c9f5d2bc4894f268dd8970883e"
  },
  {
    "title": "Kubernetes",
    "techStack": [
      "kubernetes",
      "kubernetes-deployment",
      "kubernetes-learning",
      "kubernetes-manifest-files",
      "kubernetes-manifests",
      "kubernetes-monitoring"
    ],
    "description": "📌 Master Kubernetes in One Place! From basic deployments to advanced real-time applications, this repository is a one-stop solution to learn, deploy, and manage applications in Kubernetes like a p...",
    "link": {
      "label": "github.com/Kubernetes",
      "href": "https://github.com/NotHarshhaa/Kubernetes"
    },
    "stars": 203,
    "forks": 212,
    "issues": 0,
    "lastUpdated": "2026-10-09T09:24:14Z",
    "lastCommit": "45b236f64db0c06a4c4b395111a50f6330a43b58"
  },
  {
    "title": "Dev Ops  Setup  Installations",
    "techStack": [
      "cloud-services",
      "cloud-setup",
      "devops",
      "devops-guide",
      "devops-setup-tools",
      "devops-tools"
    ],
    "description": "Comprehensive repository covering the installation and setup of essential DevOps and DevSecOps tools",
    "link": {
      "label": "github.com/DevOps_Setup-Installations",
      "href": "https://github.com/NotHarshhaa/DevOps_Setup-Installations"
    },
    "stars": 195,
    "forks": 208,
    "issues": 0,
    "lastUpdated": "2026-09-28T02:50:03Z",
    "lastCommit": "e44b1dde5f78d1687e8f804ffbe28eff73e2c4b3"
  },
  {
    "title": "Certified  Kubernetes  Administrator",
    "techStack": [
      "cka",
      "ckad",
      "ckad-exercises",
      "helm",
      "k8s",
      "kubernetes"
    ],
    "description": "Master Kubernetes from scratch and become a Certified Kubernetes Administrator (CKA)! This repository is your one-stop resource to learn Kubernetes, Helm, Operators, Prometheus, and AWS EKS with ha...",
    "link": {
      "label": "github.com/Certified_Kubernetes_Administrator",
      "href": "https://github.com/NotHarshhaa/Certified_Kubernetes_Administrator"
    },
    "stars": 166,
    "forks": 122,
    "issues": 0,
    "lastUpdated": "2026-09-19T06:02:44Z",
    "lastCommit": "0a7687b7f90931b824ea425b8b9d2372c683cd2a"
  },
  {
    "title": "A W S  Projects",
    "techStack": [
      "aws",
      "aws-apigateway",
      "aws-cli",
      "aws-cloud",
      "aws-cloudformation",
      "aws-ec2"
    ],
    "description": "Real-world AWS projects for aspiring cloud engineers — Beginner to Advanced. Covers AWS services, Infrastructure as Code, CI/CD, containers, serverless, monitoring, and more. Hands-on learning with...",
    "link": {
      "label": "github.com/AWS-Projects",
      "href": "https://github.com/NotHarshhaa/AWS-Projects"
    },
    "stars": 150,
    "forks": 73,
    "issues": 0,
    "lastUpdated": "2026-10-09T09:24:20Z",
    "lastCommit": "bb21262eef476b6ab4430e0997e26f1e6392e07a"
  },
  {
    "title": "C I  C D  E K S  Git Hub  Actions",
    "techStack": [
      "aws",
      "aws-eks",
      "cicd",
      "devops",
      "eks",
      "eks-cluster"
    ],
    "description": "A fully automated CI/CD pipeline that builds, tests, and deploys a Node.js application on Amazon EKS using GitHub Actions, Terraform, and Kubernetes.",
    "link": {
      "label": "github.com/CI-CD_EKS-GitHub_Actions",
      "href": "https://github.com/NotHarshhaa/CI-CD_EKS-GitHub_Actions"
    },
    "stars": 138,
    "forks": 119,
    "issues": 1,
    "lastUpdated": "2026-09-22T15:31:37Z",
    "lastCommit": "c83c2739ba8385db73508b7a31852fc7aa64918e"
  },
  {
    "title": "A W S  G C P  Azure  Cloud  Projects  Workshop",
    "techStack": [
      "amazon-web-services",
      "aws",
      "azure",
      "cloud-projects",
      "google-cloud-platform",
      "microsoft-azure"
    ],
    "description": "A complete, hands-on collection of AWS, Google Cloud (GCP), and Microsoft Azure projects designed to help you gain real-world experience, build your portfolio, and prepare for certifications.",
    "link": {
      "label": "github.com/AWS-GCP-Azure-Cloud-Projects-Workshop",
      "href": "https://github.com/NotHarshhaa/AWS-GCP-Azure-Cloud-Projects-Workshop"
    },
    "stars": 115,
    "forks": 52,
    "issues": 0,
    "lastUpdated": "2026-10-09T10:58:43Z",
    "lastCommit": "2918d6d05e02dd981ef9a89bcf7202afde64d6e3"
  },
  {
    "title": "Azure all in one",
    "techStack": [
      "azure",
      "azure-app-service",
      "azure-automation",
      "azure-cli",
      "azure-cloud",
      "azure-cloud-services"
    ],
    "description": "𝘼 𝙘𝙪𝙧𝙖𝙩𝙚𝙙 𝙡𝙞𝙨𝙩 𝙤𝙛 𝙖𝙬𝙚𝙨𝙤𝙢𝙚 𝘼𝙯𝙪𝙧𝙚 𝙚 𝙍𝙚𝙨𝙤𝙪𝙧𝙘𝙚, 𝙡𝙞𝙗𝙧𝙖𝙧𝙞𝙚𝙨, 𝙤𝙥𝙚𝙣 𝙨𝙤𝙪𝙧𝙘𝙚 𝙧𝙚𝙥𝙤𝙨, 𝙜𝙪𝙞𝙙𝙚𝙨, 𝙗𝙡𝙤𝙜𝙨, 𝙖𝙣𝙙 𝙤𝙩𝙝𝙚𝙧 𝙧𝙚𝙨𝙤𝙪𝙧𝙘𝙚𝙨.",
    "link": {
      "label": "github.com/azure-all_in_one",
      "href": "https://github.com/NotHarshhaa/azure-all_in_one"
    },
    "stars": 92,
    "forks": 61,
    "issues": 0,
    "lastUpdated": "2026-08-10T10:48:10Z",
    "lastCommit": "c5d20e6f4d6006e8d87d54b0f9e264360e18c4c3"
  },
  {
    "title": "Eks cluster terraform",
    "techStack": [
      "aws",
      "aws-eks",
      "deployment",
      "eks",
      "terraform",
      "terraform-modules"
    ],
    "description": "This project uses Terraform to provision an Amazon EKS Cluster on AWS. By leveraging Infrastructure as Code (IaC), we automate the deployment of Kubernetes clusters with modular and reusable Terraf...",
    "link": {
      "label": "github.com/eks-cluster-terraform",
      "href": "https://github.com/NotHarshhaa/eks-cluster-terraform"
    },
    "stars": 74,
    "forks": 68,
    "issues": 0,
    "lastUpdated": "2026-09-06T16:03:25Z",
    "lastCommit": "85af1d99301781702234e86fabf16213bbdeddf1"
  },
  {
    "title": "Dev Ops  Tool  Installer",
    "techStack": [
      "ansible",
      "devops",
      "devops-tools",
      "docker",
      "github",
      "installer"
    ],
    "description": "Automate installation/uninstallation of essential DevOps tools on Linux and Windows with a single script. Perfect for DevOps engineers and enthusiasts looking to streamline their setup process.",
    "link": {
      "label": "github.com/DevOps-Tool-Installer",
      "href": "https://github.com/NotHarshhaa/DevOps-Tool-Installer"
    },
    "stars": 64,
    "forks": 71,
    "issues": 0,
    "lastUpdated": "2026-08-27T03:13:03Z",
    "lastCommit": "b49b9dd35b4013740775bb3ce2b6c6c2e621c10f"
  },
  {
    "title": "Kubernetes dashboard",
    "techStack": [
      "health-check",
      "kubernetes",
      "kubernetes-dashboard",
      "kubernetes-metrics",
      "kubernetes-monitoring",
      "kubernetes-pods"
    ],
    "description": "This dashboard unifies multi-cluster fleet operations, real-time Metrics Server telemetry, AI/GPU accelerator observability, GitOps workflow safeguards (ArgoCD & Flux), next-gen Gateway API routing...",
    "link": {
      "label": "github.com/kubernetes-dashboard",
      "href": "https://github.com/NotHarshhaa/kubernetes-dashboard"
    },
    "stars": 59,
    "forks": 53,
    "issues": 0,
    "lastUpdated": "2026-09-13T07:17:41Z",
    "lastCommit": "76ce74c2cb8a22403c49a534468a790647ebce29"
  },
  {
    "title": "Aws billing alert terraform",
    "techStack": [
      "aws",
      "aws-billing",
      "aws-terraform",
      "terraform",
      "terraform-modules",
      "HCL"
    ],
    "description": "𝐓𝐡𝐢𝐬 𝐫𝐞𝐩𝐨𝐬𝐢𝐭𝐨𝐫𝐲 𝐜𝐨𝐧𝐭𝐚𝐢𝐧𝐬 𝐚 𝐓𝐞𝐫𝐫𝐚𝐟𝐨𝐫𝐦 𝐦𝐨𝐝𝐮𝐥𝐞 𝐭𝐡𝐚𝐭 𝐡𝐞𝐥𝐩𝐬 𝐬𝐞𝐭 𝐮𝐩 𝐀𝐖𝐒 𝐛𝐢𝐥𝐥𝐢𝐧𝐠 𝐚𝐥𝐞𝐫𝐭𝐬",
    "link": {
      "label": "github.com/aws-billing-alert-terraform",
      "href": "https://github.com/NotHarshhaa/aws-billing-alert-terraform"
    },
    "stars": 58,
    "forks": 55,
    "issues": 0,
    "lastUpdated": "2026-08-10T10:49:04Z",
    "lastCommit": "0c80125fb75a3fba44c02bc92e039aefb6627877"
  },
  {
    "title": "Cloud  Native  Dev Ops  Project",
    "techStack": [
      "aws",
      "aws-project",
      "cloud-native",
      "cloud-native-applications",
      "db",
      "devops"
    ],
    "description": "Build & deploy a Cloud-Native Full-Stack Application using Terraform, Jenkins, Docker & Kubernetes – all on AWS! 💥",
    "link": {
      "label": "github.com/Cloud-Native-DevOps-Project",
      "href": "https://github.com/NotHarshhaa/Cloud-Native-DevOps-Project"
    },
    "stars": 35,
    "forks": 44,
    "issues": 0,
    "lastUpdated": "2026-10-04T00:58:39Z",
    "lastCommit": "b9abb4e7ac0f05a45dfc0cd22fa65ce4dfd2b03b"
  },
  {
    "title": "Ai platform engineering handbook",
    "techStack": [],
    "description": "Production-grade DevOps, MLOps, and Platform Engineering documentation with real-world AI infrastructure design, automation pipelines, and cloud-native architecture patterns.",
    "link": {
      "label": "github.com/ai-platform-engineering-handbook",
      "href": "https://github.com/NotHarshhaa/ai-platform-engineering-handbook"
    },
    "stars": 35,
    "forks": 15,
    "issues": 1,
    "lastUpdated": "2026-10-08T00:31:18Z",
    "lastCommit": "f4680a501b8c58ba0382283f81b1ba5d3333fda1"
  },
  {
    "title": "From  Docker to  Kubernetes",
    "techStack": [
      "docker",
      "docker-compose",
      "docker-container",
      "docker-kubernetes",
      "docker-tutorial",
      "kubernetes"
    ],
    "description": "A hands-on learning repository to help you master containerization and orchestration — starting with Docker fundamentals and progressing to real-world Kubernetes deployments. Ideal for developers,...",
    "link": {
      "label": "github.com/From-Docker-to-Kubernetes",
      "href": "https://github.com/NotHarshhaa/From-Docker-to-Kubernetes"
    },
    "stars": 34,
    "forks": 34,
    "issues": 2,
    "lastUpdated": "2026-10-09T09:24:02Z",
    "lastCommit": "80408e3d8f4838dfe2172a6d2ceab9e533c0680c"
  },
  {
    "title": "A W S  Dev Ops  Real  Time  Deployment",
    "techStack": [
      "automation",
      "aws",
      "aws-codebuild",
      "aws-codedeploy",
      "aws-codepipeline",
      "cicd"
    ],
    "description": "🚀 Production-ready AWS DevOps CI/CD pipeline automating multi-environment deployments (Dev ➔ Staging ➔ Prod) using AWS CodePipeline, CodeBuild, CodeDeploy, and hardened Nginx.",
    "link": {
      "label": "github.com/AWS-DevOps_Real-Time_Deployment",
      "href": "https://github.com/NotHarshhaa/AWS-DevOps_Real-Time_Deployment"
    },
    "stars": 30,
    "forks": 69,
    "issues": 0,
    "lastUpdated": "2026-09-03T14:32:46Z",
    "lastCommit": "8e46b103e4c3722786a9a042eb4c1c8e6a13a4a8"
  },
  {
    "title": "Learning  Prometheus",
    "techStack": [
      "prometheus",
      "prometheus-client",
      "prometheus-learning",
      "prometheus-metrics",
      "prometheus-operator"
    ],
    "description": "𝘼 𝙧𝙚𝙥𝙤𝙨𝙞𝙩𝙤𝙧𝙮 𝙙𝙚𝙙𝙞𝙘𝙖𝙩𝙚𝙙 𝙩𝙤 𝙚𝙭𝙥𝙡𝙤𝙧𝙞𝙣𝙜 𝙖𝙣𝙙 𝙞𝙢𝙥𝙡𝙚𝙢𝙚𝙣𝙩𝙞𝙣𝙜 𝙋𝙧𝙤𝙢𝙚𝙩𝙝𝙚𝙪𝙨 𝙛𝙤𝙧 𝙢𝙤𝙣𝙞𝙩𝙤𝙧𝙞𝙣𝙜 𝙖𝙣𝙙 𝙤𝙗𝙨𝙚𝙧𝙫𝙖𝙗𝙞𝙡𝙞𝙩𝙮 𝙞𝙣 𝙆𝙪𝙗𝙚𝙧...",
    "link": {
      "label": "github.com/Learning-Prometheus",
      "href": "https://github.com/NotHarshhaa/Learning-Prometheus"
    },
    "stars": 22,
    "forks": 44,
    "issues": 0,
    "lastUpdated": "2026-07-16T17:33:32Z",
    "lastCommit": "c79e4344f3531c08ab27ced74bfa2b018d8fe4e0"
  },
  {
    "title": "A W S  E K S  Terraform",
    "techStack": [
      "aws-ec2",
      "aws-ecr",
      "aws-s3",
      "aws-terraform",
      "eks",
      "eks-cluster"
    ],
    "description": "PROVISION EKS (Amazon Elastic Kubernetes Service) CLUSTER ON AWS USING TERRAFORM",
    "link": {
      "label": "github.com/AWS-EKS_Terraform",
      "href": "https://github.com/NotHarshhaa/AWS-EKS_Terraform"
    },
    "stars": 21,
    "forks": 57,
    "issues": 0,
    "lastUpdated": "2026-09-14T14:19:26Z",
    "lastCommit": "bd77ff8270a7ac5c75a126c8a05a4ff2f32e6563"
  },
  {
    "title": "A W S  Terraform  Workshop",
    "techStack": [
      "automation",
      "aws",
      "aws-workshops",
      "terraform",
      "terraform-workshop",
      "Shell"
    ],
    "description": "//  A beginner-friendly guide to setting up AWS infrastructure using Terraform! Learn how to automate and manage cloud resources with ease.  //",
    "link": {
      "label": "github.com/AWS-Terraform-Workshop",
      "href": "https://github.com/NotHarshhaa/AWS-Terraform-Workshop"
    },
    "stars": 18,
    "forks": 26,
    "issues": 1,
    "lastUpdated": "2026-06-04T09:26:19Z",
    "lastCommit": "dc06ce5ad9f1db755497112ed59a65cbfc1379b9"
  },
  {
    "title": "Devops monitoring in a box",
    "techStack": [
      "alertmanager",
      "devops-monitoring",
      "docker",
      "docker-compose",
      "grafana",
      "grafana-dashboard"
    ],
    "description": "This project provides a ready-to-use advanced monitoring platform for DevOps engineers and beginners. With just one command, you get Prometheus, Grafana, Loki, Alertmanager, Node Exporter",
    "link": {
      "label": "github.com/devops-monitoring-in-a-box",
      "href": "https://github.com/NotHarshhaa/devops-monitoring-in-a-box"
    },
    "stars": 18,
    "forks": 21,
    "issues": 1,
    "lastUpdated": "2026-10-09T09:24:16Z",
    "lastCommit": "f251d9d5bf5eead29aa18dc08000c36ecbdda9bf"
  },
  {
    "title": "Zomato  Clone",
    "techStack": [
      "devsecops",
      "devsecops-best-practices",
      "devsecops-pipeline",
      "reactjs",
      "zomato-app",
      "zomato-clone"
    ],
    "description": "This repository is a full-stack food delivery application inspired by Zomato. It includes a React.js frontend and integrates DevSecOps practices to ensure a secure and automated deployment pipeline.",
    "link": {
      "label": "github.com/Zomato-Clone",
      "href": "https://github.com/NotHarshhaa/Zomato-Clone"
    },
    "stars": 17,
    "forks": 87,
    "issues": 2,
    "lastUpdated": "2026-09-04T05:47:24Z",
    "lastCommit": "823466a188d4853ca15308d6194a49d04582b685"
  },
  {
    "title": "Deployment of super  Mario on  Kubernetes using terraform",
    "techStack": [
      "aws",
      "aws-ec2",
      "eks",
      "supermario",
      "terraform",
      "terraform-modules"
    ],
    "description": "Super Mario is a legendary game we all cherish! In this project, we will deploy Super Mario on Amazon EKS (Elastic Kubernetes Service) using Terraform and manage infrastructure with AWS resources.",
    "link": {
      "label": "github.com/Deployment-of-super-Mario-on-Kubernetes-using-terraform",
      "href": "https://github.com/NotHarshhaa/Deployment-of-super-Mario-on-Kubernetes-using-terraform"
    },
    "stars": 14,
    "forks": 37,
    "issues": 1,
    "lastUpdated": "2026-09-04T05:31:17Z",
    "lastCommit": "882896355b69b1f3a94deed097829db93756f1ae"
  },
  {
    "title": "Awesome devops cloud",
    "techStack": [
      "JavaScript"
    ],
    "description": "A curated list for DevOps and Cloud Engineering. Explore the most useful tools, platforms, utilities, and guides — beautifully categorized and easily searchable in one place.",
    "link": {
      "label": "github.com/awesome-devops-cloud",
      "href": "https://github.com/NotHarshhaa/awesome-devops-cloud"
    },
    "stars": 14,
    "forks": 19,
    "issues": 8,
    "lastUpdated": "2026-08-13T13:46:23Z",
    "lastCommit": "d0a9a3bca984b55babd7750e7159faa4b61d2192"
  },
  {
    "title": "Cv portfolio",
    "techStack": [
      "cv",
      "javascript",
      "nextjs",
      "personal-cv",
      "tailwindcss",
      "typescript"
    ],
    "description": "A modern, responsive, and print-ready CV portfolio showcasing hands-on expertise across Platform Engineering, DevOps, AI Infrastructure, GenAI, AI Agents, MCP, LLMOps, and AI Product Development.",
    "link": {
      "label": "github.com/cv-portfolio",
      "href": "https://github.com/NotHarshhaa/cv-portfolio"
    },
    "stars": 13,
    "forks": 12,
    "issues": 0,
    "lastUpdated": "2026-10-02T22:09:28Z",
    "lastCommit": "eacb3e89619766b51edd7794551d5d9dde39f472"
  },
  {
    "title": "Devops project templates",
    "techStack": [
      "HCL",
      "Shell",
      "JavaScript",
      "CSS",
      "HTML"
    ],
    "description": "A collection of production-ready DevOps & Cloud project templates designed for DevOps Engineers, Cloud Engineers, and Platform Engineers.",
    "link": {
      "label": "github.com/devops-project-templates",
      "href": "https://github.com/NotHarshhaa/devops-project-templates"
    },
    "stars": 12,
    "forks": 5,
    "issues": 0,
    "lastUpdated": "2026-08-27T03:14:23Z",
    "lastCommit": "6a322f381ee00547ce805cefbe44570763122679"
  },
  {
    "title": "Github repo status tracker",
    "techStack": [
      "TypeScript",
      "Python",
      "Shell",
      "JavaScript",
      "CSS"
    ],
    "description": "This project automates the tracking of multiple GitHub repositories, providing a real-time status update on key repository metrics. The status information is dynamically updated and displayed in th...",
    "link": {
      "label": "github.com/github-repo-status-tracker",
      "href": "https://github.com/NotHarshhaa/github-repo-status-tracker"
    },
    "stars": 12,
    "forks": 18,
    "issues": 0,
    "lastUpdated": "2026-10-09T12:51:17Z",
    "lastCommit": "2260518cb8692d9475cc46849182071f860f3113"
  },
  {
    "title": "Tf ecr ecs gh deploy",
    "techStack": [
      "aws",
      "aws-ecs",
      "github-actions",
      "python",
      "python-aws",
      "terraform"
    ],
    "description": "This project automates the deployment of a Python application to AWS Elastic Container Service (ECS) using GitHub Actions, Docker, and Terraform.",
    "link": {
      "label": "github.com/tf-ecr-ecs-gh-deploy",
      "href": "https://github.com/NotHarshhaa/tf-ecr-ecs-gh-deploy"
    },
    "stars": 11,
    "forks": 24,
    "issues": 0,
    "lastUpdated": "2026-06-11T21:58:36Z",
    "lastCommit": "76a6209746bbf4c0fa3463bcc89ea9fad47ec9d1"
  },
  {
    "title": "Links portfolio",
    "techStack": [
      "css",
      "javascript",
      "links",
      "nextjs",
      "personal-site",
      "personal-website"
    ],
    "description": "✨ Links to my social media.",
    "link": {
      "label": "github.com/links-portfolio",
      "href": "https://github.com/NotHarshhaa/links-portfolio"
    },
    "stars": 11,
    "forks": 9,
    "issues": 0,
    "lastUpdated": "2026-09-30T18:09:26Z",
    "lastCommit": "a9309dfe6a42b015e0ef2e2d72c099330f8a595c"
  },
  {
    "title": "Jenkins  Terraform  A W S  Infra",
    "techStack": [
      "aws",
      "aws-ec2",
      "jenkins",
      "terraform",
      "terraform-aws",
      "terraform-cloud"
    ],
    "description": "Terraform scripts to automate the provisioning of AWS infrastructure, including VPC, Subnets, Security Groups, EC2 instances, and Jenkins integration for Infrastructure as Code (IaC) deployment.",
    "link": {
      "label": "github.com/Jenkins-Terraform-AWS-Infra",
      "href": "https://github.com/NotHarshhaa/Jenkins-Terraform-AWS-Infra"
    },
    "stars": 10,
    "forks": 26,
    "issues": 0,
    "lastUpdated": "2026-04-26T11:51:26Z",
    "lastCommit": "2fec48f59b8ea0a59f03314763fe18fc4fe05fbd"
  },
  {
    "title": "Devops skills",
    "techStack": [
      "agent-skill",
      "agent-skills",
      "agents",
      "devops-agent-skills",
      "devops-agents",
      "devops-skills"
    ],
    "description": "A collection of reusable DevOps Agent Skills for incident response, infrastructure auditing, Kubernetes, Terraform, CI/CD, observability, security, and platform engineering.",
    "link": {
      "label": "github.com/devops-skills",
      "href": "https://github.com/NotHarshhaa/devops-skills"
    },
    "stars": 9,
    "forks": 4,
    "issues": 0,
    "lastUpdated": "2026-10-09T09:24:31Z",
    "lastCommit": "3605f9452e331d984a2a119e5a00763ecdff23e5"
  },
  {
    "title": "Prodevopsguytech.com",
    "techStack": [
      "javascript",
      "nextjs",
      "tailwindcss",
      "typescript",
      "TypeScript",
      "JavaScript"
    ],
    "description": "Web of ProDevOpsGuy Tech is a passionate community built for DevOps and Cloud enthusiasts, learners, and professionals. Our mission is to empower individuals by providing hands-on, real-world proje...",
    "link": {
      "label": "github.com/prodevopsguytech.com",
      "href": "https://github.com/NotHarshhaa/prodevopsguytech.com"
    },
    "stars": 7,
    "forks": 3,
    "issues": 0,
    "lastUpdated": "2025-09-20T15:11:52Z",
    "lastCommit": "502ddc5f8000c7825e970b2bf866c47f89aa69c6"
  },
  {
    "title": "Cloud native monitoring app",
    "techStack": [
      "aws",
      "aws-ecr-terraform",
      "docker",
      "ecr",
      "flash",
      "python"
    ],
    "description": "This is a monitoring app built with Python, and it would be containerized with Docker and deployed to EKS",
    "link": {
      "label": "github.com/cloud-native-monitoring-app",
      "href": "https://github.com/NotHarshhaa/cloud-native-monitoring-app"
    },
    "stars": 7,
    "forks": 18,
    "issues": 0,
    "lastUpdated": "2025-04-15T18:04:31Z",
    "lastCommit": "15102a44dc31d8f340e4ae1ca83db337b488c483"
  },
  {
    "title": "Devops environment toolkit beginners",
    "techStack": [
      "devops",
      "devops-environment",
      "devops-tools",
      "devops-tools-support",
      "installation-scripts",
      "setup-development-environment"
    ],
    "description": "This repo provides a ready-to-use local setup with all the essential tools you need before starting your DevOps learning journey.",
    "link": {
      "label": "github.com/devops-environment-toolkit-beginners",
      "href": "https://github.com/NotHarshhaa/devops-environment-toolkit-beginners"
    },
    "stars": 7,
    "forks": 5,
    "issues": 0,
    "lastUpdated": "2026-06-02T16:44:32Z",
    "lastCommit": "fa4bdc02a6e9fdf5c8f48faf9661c0bd411ab9b0"
  },
  {
    "title": "Uber clone",
    "techStack": [
      "JavaScript",
      "HCL",
      "CSS",
      "Dockerfile"
    ],
    "description": "This repository is a full-stack transportation application inspired by Uber. It includes a React.js frontend and integrates DevSecOps practices to ensure a secure and automated deployment pipeline.",
    "link": {
      "label": "github.com/uber-clone",
      "href": "https://github.com/NotHarshhaa/uber-clone"
    },
    "stars": 7,
    "forks": 13,
    "issues": 0,
    "lastUpdated": "2026-10-06T17:41:13Z",
    "lastCommit": "d54f10fc513fc2fdd33f92041ae0f9dfaac36c43"
  },
  {
    "title": "Aws infra generator",
    "techStack": [
      "aws",
      "aws-infra",
      "aws-infra-gen",
      "aws-infrastructure-automation",
      "cloudformation",
      "infra-gen"
    ],
    "description": "A platform engineering tool that generates production-ready AWS infrastructure templates using Terraform or CloudFormation based on user-selected services.",
    "link": {
      "label": "github.com/aws-infra-generator",
      "href": "https://github.com/NotHarshhaa/aws-infra-generator"
    },
    "stars": 7,
    "forks": 5,
    "issues": 0,
    "lastUpdated": "2026-09-03T14:32:55Z",
    "lastCommit": "8fe2ab96143dd48d8d0659f487ccad940e6e9ce1"
  },
  {
    "title": "Devops project generator",
    "techStack": [
      "devops",
      "devops-gen",
      "devops-project",
      "devops-project-generator",
      "project-gen",
      "project-generator"
    ],
    "description": "A CLI & UI Tool that generates production-ready DevOps repositories based on user-selected options like CI/CD, infrastructure, deployment, environments, observability, and security.",
    "link": {
      "label": "github.com/devops-project-generator",
      "href": "https://github.com/NotHarshhaa/devops-project-generator"
    },
    "stars": 7,
    "forks": 10,
    "issues": 0,
    "lastUpdated": "2026-10-09T09:24:34Z",
    "lastCommit": "2ffa5d1b23d5bc4493a8f12eb76551b97dd31d4b"
  },
  {
    "title": "Azure devops zero to hero",
    "techStack": [
      "azure-artifacts",
      "azure-boards",
      "azure-devops",
      "azure-pipelines",
      "azure-repos",
      "azure-test-plans"
    ],
    "description": "Azure DevOps Zero to Hero — comprehensive guide to master Azure DevOps from fundamentals to advanced use. Learn Boards, Pipelines, Repos, Artifacts & Test Plans with practical, step-by-step content...",
    "link": {
      "label": "github.com/azure-devops-zero-to-hero",
      "href": "https://github.com/NotHarshhaa/azure-devops-zero-to-hero"
    },
    "stars": 7,
    "forks": 11,
    "issues": 0,
    "lastUpdated": "2026-09-15T09:04:38Z",
    "lastCommit": "9664378defd5705f45e56f27221fd9c9ca9052d7"
  },
  {
    "title": "Projects.prodevopsguytech.com",
    "techStack": [
      "css",
      "devops",
      "devops-learning",
      "devops-practice-project-space",
      "devops-projects",
      "farmer-motion"
    ],
    "description": "A website showcasing a curated list of major real-time DevOps and Cloud projects, ranging from beginner to advanced levels. Built using Next.js and styled with Tailwind CSS, this project leverages...",
    "link": {
      "label": "github.com/projects.prodevopsguytech.com",
      "href": "https://github.com/NotHarshhaa/projects.prodevopsguytech.com"
    },
    "stars": 6,
    "forks": 9,
    "issues": 0,
    "lastUpdated": "2026-09-07T07:01:27Z",
    "lastCommit": "3204be5a70d79a93ae68a39e39bfbad514ebafc1"
  },
  {
    "title": "Devops tools setups installations",
    "techStack": [
      "TypeScript",
      "MDX",
      "CSS",
      "JavaScript"
    ],
    "description": "Master DevOps Tools Installation & Configuration — Your comprehensive guide to setting up a professional DevOps environment with step-by-step tutorials and best practices.",
    "link": {
      "label": "github.com/devops-tools-setups-installations",
      "href": "https://github.com/NotHarshhaa/devops-tools-setups-installations"
    },
    "stars": 6,
    "forks": 10,
    "issues": 0,
    "lastUpdated": "2026-05-09T18:19:37Z",
    "lastCommit": "b35a85123c3a5e8d219bee80742cb32cf0b4f446"
  },
  {
    "title": "Interviews.prodevopsguytech.com",
    "techStack": [
      "TypeScript",
      "MDX",
      "CSS",
      "JavaScript"
    ],
    "description": "This project powers a modern web UI designed to help DevOps professionals prepare for interviews with curated, categorized, and regularly updated questions.",
    "link": {
      "label": "github.com/interviews.prodevopsguytech.com",
      "href": "https://github.com/NotHarshhaa/interviews.prodevopsguytech.com"
    },
    "stars": 6,
    "forks": 3,
    "issues": 0,
    "lastUpdated": "2026-06-13T10:42:49Z",
    "lastCommit": "fd5d26969e6907f9b1aae0e57a738946870e88b8"
  },
  {
    "title": "Personal portfolio",
    "techStack": [
      "css",
      "javascript",
      "nodejs",
      "tailwindcss",
      "typescript",
      "TypeScript"
    ],
    "description": "✨ My personal portfolio showcasing my work and skills.",
    "link": {
      "label": "github.com/personal-portfolio",
      "href": "https://github.com/NotHarshhaa/personal-portfolio"
    },
    "stars": 6,
    "forks": 7,
    "issues": 0,
    "lastUpdated": "2026-09-30T17:51:00Z",
    "lastCommit": "462f4821383cdfb92e62603da264c94306b263cc"
  },
  {
    "title": "Devops incident agent",
    "techStack": [
      "Python",
      "Dockerfile"
    ],
    "description": "An open-source AI agent that automatically investigates DevOps incidents by analyzing metrics, logs, Kubernetes events, deployments, and CI/CD pipelines to identify root causes and recommend fixes.",
    "link": {
      "label": "github.com/devops-incident-agent",
      "href": "https://github.com/NotHarshhaa/devops-incident-agent"
    },
    "stars": 6,
    "forks": 3,
    "issues": 7,
    "lastUpdated": "2026-10-01T08:26:37Z",
    "lastCommit": "ffc272d5d26758bc89dfff64a2ae878256230568"
  },
  {
    "title": "Prodevopsguy.xyz",
    "techStack": [
      "Astro",
      "TypeScript",
      "CSS",
      "JavaScript",
      "Shell"
    ],
    "description": "A minimal, accessible and SEO-friendly Astro blog theme",
    "link": {
      "label": "github.com/prodevopsguy.xyz",
      "href": "https://github.com/NotHarshhaa/prodevopsguy.xyz"
    },
    "stars": 5,
    "forks": 2,
    "issues": 1,
    "lastUpdated": "2025-02-22T19:57:13Z",
    "lastCommit": "97fb1167d78a6f050c4031432dc5f5f5a5b1de5a"
  },
  {
    "title": "Jobs.prodevopsguytech.com",
    "techStack": [
      "devopsjobs",
      "job-board",
      "job-portal",
      "jobs-search",
      "jobsearch",
      "nextjs14"
    ],
    "description": "Find your dream DevOps, SRE, Platform Engineering, and Cloud jobs — all in one place. No ads. No fees. Just high-quality job listings updated daily. [COMING SOON - WIP]",
    "link": {
      "label": "github.com/jobs.prodevopsguytech.com",
      "href": "https://github.com/NotHarshhaa/jobs.prodevopsguytech.com"
    },
    "stars": 4,
    "forks": 2,
    "issues": 0,
    "lastUpdated": "2026-02-22T15:07:20Z",
    "lastCommit": "1ec416a57a8e06739aecf4c504308bf6b369f880"
  },
  {
    "title": "Dev Ops  Engineering",
    "techStack": [
      "TypeScript",
      "MDX",
      "JavaScript",
      "CSS"
    ],
    "description": "Personal space to explore, experiment, and grow in the DevOps field. It's not meant to be a complete toolkit or production-ready solution just a place to try new ideas, test tools, and build unique...",
    "link": {
      "label": "github.com/DevOps-Engineering",
      "href": "https://github.com/NotHarshhaa/DevOps-Engineering"
    },
    "stars": 4,
    "forks": 9,
    "issues": 0,
    "lastUpdated": "2025-12-18T10:58:39Z",
    "lastCommit": "b3c5d433b8298ecf28baae97aa5ec030bb95f038"
  },
  {
    "title": "Cheatsheet.prodevopsguytech.com",
    "techStack": [],
    "description": "Welcome to the DevOps Tools Cheatsheet Collection (UI-BASED) – your go-to resource for mastering DevOps tools and technologies!",
    "link": {
      "label": "github.com/cheatsheet.prodevopsguytech.com",
      "href": "https://github.com/NotHarshhaa/cheatsheet.prodevopsguytech.com"
    },
    "stars": 4,
    "forks": 0,
    "issues": 0,
    "lastUpdated": "2026-06-30T23:07:05Z",
    "lastCommit": "bbbbbb4721e7e3dbe971bd03edad3aaf7455369f"
  },
  {
    "title": "Ai question paper generator",
    "techStack": [
      "TypeScript",
      "Python",
      "Shell",
      "HCL",
      "CSS"
    ],
    "description": "An intelligent full-stack system that automatically generates DevOps and AWS certification & university-style question papers using NLP and Machine Learning techniques. Includes an interactive 2,50...",
    "link": {
      "label": "github.com/ai-question-paper-generator",
      "href": "https://github.com/NotHarshhaa/ai-question-paper-generator"
    },
    "stars": 4,
    "forks": 1,
    "issues": 0,
    "lastUpdated": "2026-09-29T09:10:14Z",
    "lastCommit": "be2441c97cfa3402899e4da57d99e24b886add9c"
  },
  {
    "title": "Devops mcp",
    "techStack": [
      "argocd",
      "devops",
      "gitops",
      "kubectl",
      "kubernetes",
      "mcp"
    ],
    "description": "Unified MCP server for DevOps engineers — query and manage Kubernetes, ArgoCD, Prometheus, and PagerDuty from any MCP-compatible AI agent.",
    "link": {
      "label": "github.com/devops-mcp",
      "href": "https://github.com/NotHarshhaa/devops-mcp"
    },
    "stars": 4,
    "forks": 1,
    "issues": 0,
    "lastUpdated": "2026-10-09T09:24:11Z",
    "lastCommit": "b3badd7157e7a8a5a43ddbb135faf31a6f1ea8fc"
  },
  {
    "title": "Status.prodevopsguytech.com",
    "techStack": [
      "JavaScript",
      "CSS"
    ],
    "description": "A modern, responsive status dashboard for monitoring the health and up-time of our web services and applications. ",
    "link": {
      "label": "github.com/status.prodevopsguytech.com",
      "href": "https://github.com/NotHarshhaa/status.prodevopsguytech.com"
    },
    "stars": 3,
    "forks": 8,
    "issues": 0,
    "lastUpdated": "2026-10-08T17:50:51Z",
    "lastCommit": "43a24c497ac6f858ad45911803ac837c765c1010"
  },
  {
    "title": "Prodevopsguy.hashnode.dev",
    "techStack": [],
    "description": "Backups of my blogs",
    "link": {
      "label": "github.com/prodevopsguy.hashnode.dev",
      "href": "https://github.com/NotHarshhaa/prodevopsguy.hashnode.dev"
    },
    "stars": 3,
    "forks": 10,
    "issues": 0,
    "lastUpdated": "2025-11-23T06:50:31Z",
    "lastCommit": "ef6cd275ae9734bd3b8d21feb83993374f383ef4"
  },
  {
    "title": "K8s learning platform",
    "techStack": [
      "TypeScript",
      "CSS",
      "JavaScript",
      "Shell"
    ],
    "description": "A comprehensive learning platform covering Kubernetes administration, Helm package management, operators, and monitoring. Master K8s with hands-on examples, real-world projects, and expert guidance.",
    "link": {
      "label": "github.com/k8s-learning-platform",
      "href": "https://github.com/NotHarshhaa/k8s-learning-platform"
    },
    "stars": 3,
    "forks": 4,
    "issues": 0,
    "lastUpdated": "2026-01-13T22:43:56Z",
    "lastCommit": "b0dc30592f1c62cdd9b81088d84ab37d87fa9c48"
  },
  {
    "title": "Home of best devops resources",
    "techStack": [
      "TypeScript",
      "CSS",
      "JavaScript"
    ],
    "description": "A curated collection of the \"Home of Best DevOps resources\" — with live UI demos and GitHub source links.",
    "link": {
      "label": "github.com/home-of-best-devops-resources",
      "href": "https://github.com/NotHarshhaa/home-of-best-devops-resources"
    },
    "stars": 3,
    "forks": 3,
    "issues": 0,
    "lastUpdated": "2025-12-18T11:01:30Z",
    "lastCommit": "4d1f9a8bb77876cca4b5d05654dc198667cb18ed"
  },
  {
    "title": "Cloud billing automation",
    "techStack": [
      "Python",
      "Batchfile"
    ],
    "description": "A DevOps-focused cloud billing automation tool that enables Cloud and DevOps Engineers to monitor, govern, and optimize cloud costs using automated scripts, alerts, and infrastructure cost controls.",
    "link": {
      "label": "github.com/cloud-billing-automation",
      "href": "https://github.com/NotHarshhaa/cloud-billing-automation"
    },
    "stars": 3,
    "forks": 7,
    "issues": 0,
    "lastUpdated": "2026-07-30T11:52:38Z",
    "lastCommit": "a63df46cd7a3dda1db69cd0218bd86a2b3da9530"
  },
  {
    "title": "Prodevopsguytech v2",
    "techStack": [
      "cloud",
      "devops",
      "devops-community",
      "nextjs14",
      "shadn-ui",
      "tailwindcss"
    ],
    "description": "Home of ProDevOpsGuy Tech Community Website",
    "link": {
      "label": "github.com/prodevopsguytech-v2",
      "href": "https://github.com/NotHarshhaa/prodevopsguytech-v2"
    },
    "stars": 3,
    "forks": 3,
    "issues": 0,
    "lastUpdated": "2026-09-14T18:12:41Z",
    "lastCommit": "f367a1c6d6a5f9af5978c0c87fd54e4076c721b9"
  },
  {
    "title": "Mlops project generator",
    "techStack": [
      "mlops",
      "mlops-project",
      "mlops-template",
      "pytorch",
      "scikit-learn",
      "tensorflow"
    ],
    "description": "A CLI & UI tool that generates production-ready MLOps project templates for Scikit-learn, PyTorch, and TensorFlow.",
    "link": {
      "label": "github.com/mlops-project-generator",
      "href": "https://github.com/NotHarshhaa/mlops-project-generator"
    },
    "stars": 3,
    "forks": 2,
    "issues": 0,
    "lastUpdated": "2026-09-01T09:43:39Z",
    "lastCommit": "90cc314ec1cbeceda66b63d89f984f50eb183272"
  },
  {
    "title": "Terraform cost predictor",
    "techStack": [
      "TypeScript",
      "Python",
      "CSS",
      "Dockerfile",
      "JavaScript"
    ],
    "description": "Terraform Cost Predictor is an ML-powered tool that analyzes Terraform infrastructure configurations and predicts the estimated monthly cloud cost before deployment.",
    "link": {
      "label": "github.com/terraform-cost-predictor",
      "href": "https://github.com/NotHarshhaa/terraform-cost-predictor"
    },
    "stars": 2,
    "forks": 4,
    "issues": 0,
    "lastUpdated": "2026-09-27T07:56:31Z",
    "lastCommit": "11e2a3a3bb760c0a5a78a817b292ef4cc3a91327"
  },
  {
    "title": "Mlflow k8s operator",
    "techStack": [
      "ai",
      "data-scientist",
      "kubernetes",
      "kubernetes-operator",
      "machine-learning",
      "mlflow-tracking"
    ],
    "description": "A Kubernetes operator that auto-provisions MLflow tracking servers, model registries, and artifact stores as CRDs so data scientists never touch kubectl.",
    "link": {
      "label": "github.com/mlflow-k8s-operator",
      "href": "https://github.com/NotHarshhaa/mlflow-k8s-operator"
    },
    "stars": 2,
    "forks": 0,
    "issues": 0,
    "lastUpdated": "2026-05-15T13:10:52Z",
    "lastCommit": "9653fc237f4e1b472f15309d09bb46126e52ea97"
  },
  {
    "title": "Personal blog",
    "techStack": [
      "blog",
      "devops-blogs",
      "javascript",
      "nextjs",
      "personal-blog",
      "tailwindcss"
    ],
    "description": "A personal blog site for DevOps & Cloud, AI Space based on Typescript, Next.js, TailwindCSS.",
    "link": {
      "label": "github.com/personal-blog",
      "href": "https://github.com/NotHarshhaa/personal-blog"
    },
    "stars": 2,
    "forks": 4,
    "issues": 0,
    "lastUpdated": "2026-10-05T19:20:43Z",
    "lastCommit": "dda5f0f64a3a88f27b7c2de052b1402158d515d2"
  },
  {
    "title": "Internal developer platform cli",
    "techStack": [
      "Python",
      "TypeScript",
      "CSS",
      "JavaScript"
    ],
    "description": "A powerful CLI & Web tool that enables self-service infrastructure and service creation for developers, following modern Platform Engineering principles.",
    "link": {
      "label": "github.com/internal-developer-platform-cli",
      "href": "https://github.com/NotHarshhaa/internal-developer-platform-cli"
    },
    "stars": 2,
    "forks": 2,
    "issues": 0,
    "lastUpdated": "2026-08-28T07:38:40Z",
    "lastCommit": "af6175e6acce9716d330d31a6d49d0f3b42199c2"
  },
  {
    "title": "Kube ctx manager",
    "techStack": [
      "bash",
      "context-switching",
      "devops",
      "fuzzy-search",
      "fzf",
      "kubeconfig"
    ],
    "description": "A smart shell plugin for kubectl power users fuzzy context switching, auto-suggested aliases, and prod safeguards built right into your terminal.",
    "link": {
      "label": "github.com/kube-ctx-manager",
      "href": "https://github.com/NotHarshhaa/kube-ctx-manager"
    },
    "stars": 2,
    "forks": 0,
    "issues": 0,
    "lastUpdated": "2026-07-06T09:17:54Z",
    "lastCommit": "153acfa316d4737439299fa746025829a61216b9"
  },
  {
    "title": "Jenkins plus",
    "techStack": [
      "TypeScript",
      "Groovy",
      "Go",
      "HCL",
      "Shell"
    ],
    "description": "A batteries-included Jenkins distribution — 40+ pre-configured plugins, modern React dashboard, JCasC bootstrap, and one-command deployment via Docker, Helm, or Terraform.",
    "link": {
      "label": "github.com/jenkins-plus",
      "href": "https://github.com/NotHarshhaa/jenkins-plus"
    },
    "stars": 2,
    "forks": 0,
    "issues": 0,
    "lastUpdated": "2026-08-27T03:14:16Z",
    "lastCommit": "ef37afd0422dabdb0cce875c6e281340aacff0b4"
  },
  {
    "title": "Kubeguardian",
    "techStack": [
      "kubeguard",
      "kubeguardian",
      "kubernetes",
      "kubernetes-cluster",
      "kubernetes-monitoring",
      "Go"
    ],
    "description": "KubeGuardian is an open-source Kubernetes automation tool that continuously monitors cluster health, detects common failures, and automatically remediates issues — reducing downtime, pager alerts,...",
    "link": {
      "label": "github.com/kubeguardian",
      "href": "https://github.com/NotHarshhaa/kubeguardian"
    },
    "stars": 2,
    "forks": 2,
    "issues": 0,
    "lastUpdated": "2026-06-19T14:54:52Z",
    "lastCommit": "60a6f9cad9969651eb54b1598c68cb96a601d450"
  },
  {
    "title": "Slimify",
    "techStack": [
      "docker",
      "docker-container",
      "docker-image",
      "docker-repack",
      "dockerfile",
      "dockerignore"
    ],
    "description": "Scan. Understand. Shrink. slimify inspects any Docker image, explains exactly where the bloat is, and hands you a rewritten Dockerfile + tuned .dockerignore ready to run.",
    "link": {
      "label": "github.com/slimify",
      "href": "https://github.com/NotHarshhaa/slimify"
    },
    "stars": 2,
    "forks": 2,
    "issues": 0,
    "lastUpdated": "2026-08-20T16:32:48Z",
    "lastCommit": "da6a863606d03d79f703e66305f6e204316e9492"
  },
  {
    "title": "Pipeline forge",
    "techStack": [
      "TypeScript",
      "CSS",
      "JavaScript"
    ],
    "description": "Pipeline Forge is a developer-first tool that helps you create optimized, secure, and scalable CI/CD pipelines for modern applications without writing YAML from scratch.",
    "link": {
      "label": "github.com/pipeline-forge",
      "href": "https://github.com/NotHarshhaa/pipeline-forge"
    },
    "stars": 1,
    "forks": 1,
    "issues": 0,
    "lastUpdated": "2026-08-20T16:32:46Z",
    "lastCommit": "c959508ec3b73a4d31bca4e09d992ca31ef0d5d5"
  },
  {
    "title": "Shadcn docs nuxt starter",
    "techStack": [
      "JavaScript",
      "CSS",
      "TypeScript"
    ],
    "description": "No description provided",
    "link": {
      "label": "github.com/shadcn-docs-nuxt-starter",
      "href": "https://github.com/NotHarshhaa/shadcn-docs-nuxt-starter"
    },
    "stars": 1,
    "forks": 1,
    "issues": 0,
    "lastUpdated": "2025-05-31T16:31:56Z",
    "lastCommit": "f3e015feb8009cd96592bcb345c6097d08c2a7d5"
  },
  {
    "title": "Drift watchdog",
    "techStack": [
      "Python"
    ],
    "description": "A lightweight CLI + Prometheus exporter that continuously monitors ML model input/output distributions and fires alerts when drift is detected.",
    "link": {
      "label": "github.com/drift-watchdog",
      "href": "https://github.com/NotHarshhaa/drift-watchdog"
    },
    "stars": 1,
    "forks": 0,
    "issues": 0,
    "lastUpdated": "2026-05-01T10:48:47Z",
    "lastCommit": "26e99afef1bf5dc402f4d4d58a769be807d3c079"
  },
  {
    "title": "Awesome devops cloud ui",
    "techStack": [
      "TypeScript",
      "JavaScript",
      "CSS"
    ],
    "description": "A curated collection of beautiful, powerful, and helpful UI-based tools and resources for DevOps and Cloud professionals.",
    "link": {
      "label": "github.com/awesome-devops-cloud-ui",
      "href": "https://github.com/NotHarshhaa/awesome-devops-cloud-ui"
    },
    "stars": 1,
    "forks": 4,
    "issues": 0,
    "lastUpdated": "2025-09-27T07:19:24Z",
    "lastCommit": "6a653d711d6f4c690d9dce835e84f0c5e29739bb"
  },
  {
    "title": "Scoop bucket",
    "techStack": [],
    "description": "No description provided",
    "link": {
      "label": "github.com/scoop-bucket",
      "href": "https://github.com/NotHarshhaa/scoop-bucket"
    },
    "stars": 1,
    "forks": 0,
    "issues": 0,
    "lastUpdated": "2026-04-20T11:21:20Z",
    "lastCommit": "f04d7561fed0634eebffd76aa5fcd74bada42392"
  },
  {
    "title": "Terraview",
    "techStack": [
      "TypeScript",
      "Go",
      "CSS",
      "Dockerfile",
      "Makefile"
    ],
    "description": "A lightweight, self-hostable, git-native web UI you just drop into any Terraform repo that shows a live resource status grid (created / active / inactive / not yet provisioned) — categorized by ser...",
    "link": {
      "label": "github.com/terraview",
      "href": "https://github.com/NotHarshhaa/terraview"
    },
    "stars": 1,
    "forks": 0,
    "issues": 0,
    "lastUpdated": "2026-10-07T05:42:34Z",
    "lastCommit": "5a8d975a7340da923b8c2bfe6e82c2a4c0bf768f"
  },
  {
    "title": "Reposage",
    "techStack": [
      "Python",
      "TypeScript",
      "JavaScript",
      "CSS",
      "Dockerfile"
    ],
    "description": "Chat with any public GitHub repository using RAG — clone, index, and ask questions about a codebase's architecture, config, and workflows in natural language.",
    "link": {
      "label": "github.com/reposage",
      "href": "https://github.com/NotHarshhaa/reposage"
    },
    "stars": 1,
    "forks": 0,
    "issues": 0,
    "lastUpdated": "2026-09-07T07:01:40Z",
    "lastCommit": "1b34db16bc78a6d892eb19dfdcc509227a4dcb0d"
  },
  {
    "title": "Promptdeck",
    "techStack": [
      "TypeScript",
      "Python",
      "CSS",
      "JavaScript",
      "Dockerfile"
    ],
    "description": "Open-source platform to build, test, compare, and evaluate prompts across OpenAI, Claude, Gemini, Groq, Ollama, and more — one workspace instead of ten tabs.",
    "link": {
      "label": "github.com/promptdeck",
      "href": "https://github.com/NotHarshhaa/promptdeck"
    },
    "stars": 1,
    "forks": 0,
    "issues": 0,
    "lastUpdated": "2026-09-07T07:01:38Z",
    "lastCommit": "aa9f45b12925e41f0cfc023e1d1fa882e83ff8a8"
  },
  {
    "title": "Devops agent kit",
    "techStack": [
      "Python",
      "Go",
      "Makefile"
    ],
    "description": "Bring AI-powered reasoning to your Kubernetes, ArgoCD, and Prometheus workflows with a Go CLI, pluggable tool bindings, and dual agent brains (AutoGen + LangGraph) as submodules.",
    "link": {
      "label": "github.com/devops-agent-kit",
      "href": "https://github.com/NotHarshhaa/devops-agent-kit"
    },
    "stars": 1,
    "forks": 0,
    "issues": 0,
    "lastUpdated": "2026-10-01T08:26:29Z",
    "lastCommit": "2cff1a866e33865e04b34cfe4a9ca29b625c31d6"
  },
  {
    "title": "Mainframe mcp server",
    "techStack": [
      "ibm",
      "ibm-mainframe",
      "mainframe",
      "mainframe-mcp",
      "mcp",
      "mcp-client"
    ],
    "description": "An enterprise-grade Model Context Protocol (MCP) server for IBM z/OS environments. Bridges MCP-compatible AI agents with mainframe resources jobs, datasets, USS, and operational diagnostics using I...",
    "link": {
      "label": "github.com/mainframe-mcp-server",
      "href": "https://github.com/NotHarshhaa/mainframe-mcp-server"
    },
    "stars": 0,
    "forks": 0,
    "issues": 0,
    "lastUpdated": "2026-06-10T15:11:44Z",
    "lastCommit": "a06137f34e7da50966b6dfcff1bac347bdda061b"
  },
  {
    "title": "Devops atlasx",
    "techStack": [
      "TypeScript",
      "CSS",
      "JavaScript"
    ],
    "description": "DevOps AtlasX is a real-world knowledge platform that helps engineers quickly identify, understand, and fix production issues across modern DevOps tools.",
    "link": {
      "label": "github.com/devops-atlasx",
      "href": "https://github.com/NotHarshhaa/devops-atlasx"
    },
    "stars": 0,
    "forks": 0,
    "issues": 0,
    "lastUpdated": "2026-04-18T16:05:48Z",
    "lastCommit": "d538bd930eb7783d1472e770298e8f2cce2c6038"
  },
  {
    "title": "Itsmeharshhaa.site",
    "techStack": [
      "CSS",
      "HTML",
      "JavaScript"
    ],
    "description": "Personal Web portfolio (WIP)",
    "link": {
      "label": "github.com/itsmeharshhaa.site",
      "href": "https://github.com/NotHarshhaa/itsmeharshhaa.site"
    },
    "stars": 0,
    "forks": 1,
    "issues": 0,
    "lastUpdated": "2025-04-12T04:53:03Z",
    "lastCommit": "30a4c8e06825071d41dfcae2ac6158522768a4c0"
  },
  {
    "title": "Pod why dead",
    "techStack": [
      "cli",
      "debugging",
      "devops",
      "go",
      "k8s",
      "krew"
    ],
    "description": "One command that reconstructs the full death story of any Kubernetes pod exit reason, last logs, node pressure, events, and recommendations.",
    "link": {
      "label": "github.com/pod-why-dead",
      "href": "https://github.com/NotHarshhaa/pod-why-dead"
    },
    "stars": 0,
    "forks": 0,
    "issues": 0,
    "lastUpdated": "2026-05-01T10:18:21Z",
    "lastCommit": "d32f88fb95757fa1e26ed984069f60c58df7a5c3"
  },
  {
    "title": "Homebrew tap",
    "techStack": [
      "Ruby"
    ],
    "description": "No description provided",
    "link": {
      "label": "github.com/homebrew-tap",
      "href": "https://github.com/NotHarshhaa/homebrew-tap"
    },
    "stars": 0,
    "forks": 0,
    "issues": 0,
    "lastUpdated": "2026-06-22T08:10:01Z",
    "lastCommit": "2f8a1ffcab9ce3ab5697703c5bfbff2c6e618cac"
  },
  {
    "title": "Terraview action",
    "techStack": [
      "Go",
      "Shell",
      "Dockerfile"
    ],
    "description": "GitHub Action for Terraview — post Terraform resource status tables on pull requests, gate pipelines on drift, block pending destroys, or export audit reports.",
    "link": {
      "label": "github.com/terraview-action",
      "href": "https://github.com/NotHarshhaa/terraview-action"
    },
    "stars": 0,
    "forks": 0,
    "issues": 0,
    "lastUpdated": "2026-08-20T16:32:45Z",
    "lastCommit": "024d827fb364c66d2fdecf6f9400a57c7558398d"
  },
  {
    "title": "Cost digest bot",
    "techStack": [
      "Python",
      "Dockerfile"
    ],
    "description": "A daily Slack bot that pulls your AWS cloud spend, diffs it against last week, and posts a clean human-readable cost summary with anomaly alerts no cloud console login needed.",
    "link": {
      "label": "github.com/cost-digest-bot",
      "href": "https://github.com/NotHarshhaa/cost-digest-bot"
    },
    "stars": 0,
    "forks": 1,
    "issues": 0,
    "lastUpdated": "2026-04-03T07:23:25Z",
    "lastCommit": "d7ebacdf434f5b48d83a4a33c1d03eb2e88cc484"
  },
  {
    "title": "Aws ghost",
    "techStack": [
      "aws",
      "aws-cli",
      "cli",
      "cloud-cost",
      "cloud-engineering",
      "cost-optimization"
    ],
    "description": "Scan your AWS account for forgotten, idle, and wasteful resources with per-resource cost estimates. Read-only. No SaaS. Just a CLI.",
    "link": {
      "label": "github.com/aws-ghost",
      "href": "https://github.com/NotHarshhaa/aws-ghost"
    },
    "stars": 0,
    "forks": 1,
    "issues": 2,
    "lastUpdated": "2026-05-30T16:46:12Z",
    "lastCommit": "90db1d3dd35502cb24016511f84471a709167367"
  },
  {
    "title": "Ctxlean",
    "techStack": [
      "Python"
    ],
    "description": "Reduce LLM context bloat, control token usage, improve latency, and make AI applications more efficient — without changing the underlying model.",
    "link": {
      "label": "github.com/ctxlean",
      "href": "https://github.com/NotHarshhaa/ctxlean"
    },
    "stars": 0,
    "forks": 0,
    "issues": 0,
    "lastUpdated": "2026-08-08T14:58:14Z",
    "lastCommit": "a09c8486f67768abdf4dacb805f8f92bd9b3e677"
  }
];
